{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/root/miniconda3/envs/chatglm3/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "2024-10-01 19:34:37,630 - modelscope - INFO - Use user-specified model revision: v1.0.0\n",
      "Downloading [config.json]: 100%|██████████| 1.29k/1.29k [00:00<00:00, 1.62kB/s]\n",
      "Downloading [configuration.json]: 100%|██████████| 40.0/40.0 [00:00<00:00, 72.0B/s]\n",
      "Downloading [configuration_chatglm.py]: 100%|██████████| 2.28k/2.28k [00:00<00:00, 3.85kB/s]\n",
      "Downloading [MODEL_LICENSE]: 100%|██████████| 4.04k/4.04k [00:00<00:00, 11.9kB/s]\n",
      "Downloading [modeling_chatglm.py]: 100%|██████████| 54.3k/54.3k [00:00<00:00, 117kB/s]\n",
      "Downloading [pytorch_model-00001-of-00007.bin]:  65%|██████▌   | 1.11G/1.70G [01:32<00:49, 12.7MB/s]2024-10-01 19:36:13,029 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(107384210 bytes read, 60387950 more expected)', IncompleteRead(107384210 bytes read, 60387950 more expected)) will retry\n",
      "2024-10-01 19:36:13,033 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(39677671 bytes read, 128094489 more expected)', IncompleteRead(39677671 bytes read, 128094489 more expected)) will retry\n",
      "2024-10-01 19:36:13,043 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(45542802 bytes read, 122229358 more expected)', IncompleteRead(45542802 bytes read, 122229358 more expected)) will retry\n",
      "2024-10-01 19:36:13,046 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(165822464 bytes read, 1949696 more expected)', IncompleteRead(165822464 bytes read, 1949696 more expected)) will retry\n",
      "Downloading [pytorch_model-00001-of-00007.bin]:  85%|████████▍ | 1.45G/1.70G [01:32<00:00, 1.09GB/s]2024-10-01 19:36:13,236 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00001-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:36:13,245 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00001-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:36:13,250 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00001-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:36:13,257 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00001-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "Downloading [pytorch_model-00001-of-00007.bin]:  93%|█████████▎| 1.58G/1.70G [01:34<00:00, 196MB/s] 2024-10-01 19:36:15,393 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00001-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:36:15,437 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00001-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:36:15,438 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00001-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:36:15,448 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00001-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "Downloading [pytorch_model-00001-of-00007.bin]: 1.88GB [01:38, 112MB/s]                            2024-10-01 19:36:19,468 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00001-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:36:19,565 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00001-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:36:19,566 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00001-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:36:19,570 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00001-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00001-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "Downloading [pytorch_model-00001-of-00007.bin]: 3.03GB [02:38, 20.5MB/s]\n",
      "Downloading [pytorch_model-00002-of-00007.bin]: 100%|██████████| 1.83G/1.83G [02:35<00:00, 12.7MB/s]\n",
      "Downloading [pytorch_model-00003-of-00007.bin]:  35%|███▍      | 642M/1.80G [00:55<01:47, 11.6MB/s] 2024-10-01 19:41:13,157 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(83906560 bytes read, 83865600 more expected)', IncompleteRead(83906560 bytes read, 83865600 more expected)) will retry\n",
      "Downloading [pytorch_model-00003-of-00007.bin]:  39%|███▉      | 723M/1.80G [00:55<00:07, 157MB/s] 2024-10-01 19:41:13,162 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(143981031 bytes read, 23791129 more expected)', IncompleteRead(143981031 bytes read, 23791129 more expected)) will retry\n",
      "2024-10-01 19:41:13,179 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(114687991 bytes read, 53084169 more expected)', IncompleteRead(114687991 bytes read, 53084169 more expected)) will retry\n",
      "2024-10-01 19:41:13,192 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(165671880 bytes read, 2100280 more expected)', IncompleteRead(165671880 bytes read, 2100280 more expected)) will retry\n",
      "2024-10-01 19:41:13,323 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00003-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:41:13,349 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00003-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:41:13,359 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00003-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:41:13,360 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00003-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "Downloading [pytorch_model-00003-of-00007.bin]:  69%|██████▊   | 1.23G/1.80G [00:57<00:02, 245MB/s]2024-10-01 19:41:15,448 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00003-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:41:15,513 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00003-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:41:15,536 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00003-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:41:15,547 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00003-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "Downloading [pytorch_model-00003-of-00007.bin]:  95%|█████████▍| 1.71G/1.80G [01:01<00:00, 160MB/s]2024-10-01 19:41:19,532 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00003-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:41:19,608 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00003-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:41:19,638 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00003-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:41:19,643 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00003-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00003-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "Downloading [pytorch_model-00003-of-00007.bin]: 3.68GB [02:48, 23.5MB/s]                           \n",
      "Downloading [pytorch_model-00004-of-00007.bin]: 100%|██████████| 1.69G/1.69G [02:33<00:00, 11.8MB/s]\n",
      "Downloading [pytorch_model-00005-of-00007.bin]:  18%|█▊        | 333M/1.83G [00:09<02:19, 11.6MB/s] 2024-10-01 19:46:14,343 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(45551616 bytes read, 122220544 more expected)', IncompleteRead(45551616 bytes read, 122220544 more expected)) will retry\n",
      "2024-10-01 19:46:14,346 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(33344744 bytes read, 134427416 more expected)', IncompleteRead(33344744 bytes read, 134427416 more expected)) will retry\n",
      "2024-10-01 19:46:14,349 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(153280512 bytes read, 14491648 more expected)', IncompleteRead(153280512 bytes read, 14491648 more expected)) will retry\n",
      "2024-10-01 19:46:14,352 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(118664603 bytes read, 49107557 more expected)', IncompleteRead(118664603 bytes read, 49107557 more expected)) will retry\n",
      "2024-10-01 19:46:14,524 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00005-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:46:14,524 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00005-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:46:14,536 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00005-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:46:14,536 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00005-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "Downloading [pytorch_model-00005-of-00007.bin]:  39%|███▉      | 740M/1.83G [00:11<00:07, 168MB/s] 2024-10-01 19:46:16,693 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00005-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:46:16,694 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00005-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:46:16,702 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00005-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:46:16,705 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00005-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "Downloading [pytorch_model-00005-of-00007.bin]:  55%|█████▍    | 1.01G/1.83G [00:16<00:07, 112MB/s]2024-10-01 19:46:20,864 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00005-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:46:20,866 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00005-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:46:20,870 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00005-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:46:20,872 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00005-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00005-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "Downloading [pytorch_model-00005-of-00007.bin]: 3.13GB [02:37, 21.4MB/s]                            \n",
      "Downloading [pytorch_model-00006-of-00007.bin]:  91%|█████████ | 1.63G/1.80G [02:11<00:15, 11.6MB/s]2024-10-01 19:51:12,576 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(58695680 bytes read, 23225596 more expected)', IncompleteRead(58695680 bytes read, 23225596 more expected)) will retry\n",
      "2024-10-01 19:51:12,578 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(118505192 bytes read, 49266968 more expected)', IncompleteRead(118505192 bytes read, 49266968 more expected)) will retry\n",
      "2024-10-01 19:51:12,603 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(79896576 bytes read, 87875584 more expected)', IncompleteRead(79896576 bytes read, 87875584 more expected)) will retry\n",
      "2024-10-01 19:51:12,604 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(159375904 bytes read, 8396256 more expected)', IncompleteRead(159375904 bytes read, 8396256 more expected)) will retry\n",
      "2024-10-01 19:51:12,734 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00006-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:51:12,752 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00006-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:51:12,771 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00006-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:51:12,777 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00006-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "Downloading [pytorch_model-00006-of-00007.bin]: 2.13GB [02:13, 193MB/s]                             2024-10-01 19:51:14,892 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00006-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:51:14,929 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00006-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:51:14,931 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00006-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:51:14,950 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00006-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "Downloading [pytorch_model-00006-of-00007.bin]: 2.52GB [02:17, 129MB/s]2024-10-01 19:51:19,012 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00006-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:51:19,081 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00006-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:51:19,083 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00006-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "2024-10-01 19:51:19,088 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00006-of-00007.bin failed, reason: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=v1.0.0&FilePath=pytorch_model-00006-of-00007.bin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1007)'))) will retry\n",
      "Downloading [pytorch_model-00006-of-00007.bin]: 3.34GB [02:35, 23.1MB/s]\n",
      "Downloading [pytorch_model-00007-of-00007.bin]:  63%|██████▎   | 629M/0.98G [00:48<00:29, 13.5MB/s] 2024-10-01 19:52:44,826 - modelscope - WARNING - Downloading: /root/.cache/modelscope/hub/._____temp/ZhipuAI/chatglm3-6b/pytorch_model-00007-of-00007.bin failed, reason: ('Connection broken: IncompleteRead(17866707 bytes read, 149905453 more expected)', IncompleteRead(17866707 bytes read, 149905453 more expected)) will retry\n",
      "Downloading [pytorch_model-00007-of-00007.bin]: 1.00GB [01:28, 12.1MB/s]                            \n",
      "Downloading [pytorch_model.bin.index.json]: 100%|██████████| 20.0k/20.0k [00:00<00:00, 40.8kB/s]\n",
      "Downloading [quantization.py]: 100%|██████████| 14.3k/14.3k [00:00<00:00, 35.8kB/s]\n",
      "Downloading [README.md]: 100%|██████████| 4.37k/4.37k [00:00<00:00, 9.34kB/s]\n",
      "Downloading [tokenization_chatglm.py]: 100%|██████████| 11.0k/11.0k [00:00<00:00, 25.7kB/s]\n",
      "Downloading [tokenizer.model]: 100%|██████████| 995k/995k [00:00<00:00, 1.50MB/s]\n",
      "Downloading [tokenizer_config.json]: 100%|██████████| 244/244 [00:00<00:00, 532B/s]\n"
     ]
    }
   ],
   "source": [
    "# 实验室网络不好的时候通过modelscope下载 有断点续传\n",
    "from modelscope import snapshot_download\n",
    "model_dir = snapshot_download(\"ZhipuAI/chatglm3-6b\", revision = \"v1.0.0\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/root/.cache/modelscope/hub/ZhipuAI/chatglm3-6b\n"
     ]
    }
   ],
   "source": [
    "print(model_dir)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "chatglm3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
